GET http://localhost:8080/employee/add?firstName=Игорь&lastName=Павлов&salary=200000&departmentId=2

###
GET http://localhost:8080/employee/add?firstName=Василий&lastName=Макаров&salary=200000&departmentId=2

###
GET http://localhost:8080/employee/add?firstName=Никита&lastName=Захаров&salary=450000&departmentId=3

###
GET http://localhost:8080/employee/add?firstName=Николая&lastName=Петров&salary=500000&departmentId=2

###
GET http://localhost:8080/employee/add?firstName=Екатерина&lastName=Рябова&salary=500000&departmentId=1

###
GET http://localhost:8080/departments/max-salary?departmentId=2

###
GET http://localhost:8080/departments/min-salary?departmentId=2

###
GET http://localhost:8080/departments/all?departmentId=2

###
GET http://localhost:8080/departments/all

